### PR TITLE
Use `python3 -m pip` instead of `pip`.

### LINKED ISSUE #20: Fix pip3 install command
Hi, 

the command in the README.md should be

`pip3 install https://github.com/trezor/python-shamir-mnemonic/archive/master.zip`

otherwise it produces error:

```
> pip3 install https://github.com/trezor/python-shamir-mnemonic
Collecting https://github.com/trezor/python-shamir-mnemonic
  Downloading https://github.com/trezor/python-shamir-mnemonic
     | 112kB 513kB/s
  Cannot unpack file /tmp/pip-unpack-06wljlcu/python-shamir-mnemonic (downloaded from /tmp/pip-req-build-8xq2vzvx, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-req-build-8xq2vzvx

```

### PR DESCRIPTION
**Pull request by infokiller**
Fixes #20.

### CODE REVIEW

**Comment by matejcik** [comment]
it really doesn't though? the problem is not the pip invocation but the address

**Comment by infokiller** [comment]
Damn, you're right. Anyway, as an FYI, the correct way to invoke pip is with `python -m pip`, since pip3 is not always available. So I think this PR should be merge anyway, what do you think?

**Comment by matejcik** [comment]
can you think of a practical situation where (1) `python3` is available, and (2) `pip3` is not available, but (3) `python3 -m pip` works anyway, and (4) person using this system doesn't know enough about pip to self-correct the command?

**Comment by matejcik** [comment]
i mean, on Windows for example, in the default installation, neither `python3` nor `pip3` is available, but both `python` and `pip` are. So we'd have to drop the "3" ... but that breaks on the majority of currently existing Linux installations because it invokes python2.

**Comment by infokiller** [comment]
I can't think of any, though I remember I did run into an issue with pip3 being unavailable in one of my projects.

**Pull request closed without merging**
