### PR TITLE
Support extendable backup flag

### PR DESCRIPTION
**Pull request by andrewkozlik**
Related to spec update https://github.com/satoshilabs/slips/pull/1724.

Note that we need to get this merged and released in order for the firmware device tests to pass on the corresponding firmware branch https://github.com/trezor/trezor-firmware/compare/andrewkozlik/slip39.

### CODE REVIEW

**Review by matejcik — APPROVED** [review]
functionality LGTM.

i added a bunch of commits fixing tiny problems. please review https://github.com/trezor/python-shamir-mnemonic/pull/46/commits/706934d84a7eccff7854133c2fb681ef90658a9e in particular which is the only questionable one -- it seemed cleaner to pass the full customization string into RS1024 from the outside. but I'm not attached to that solution, i'll remove that commit if you dislike it.

**Comment by andrewkozlik** [comment]
https://github.com/trezor/python-shamir-mnemonic/pull/46/commits/a1cb726876dfafdedf8e27d3460dbf57632e7c91 Updated a comment.

The customization string `shamir_extendable` is not used in the PBKDF2 salt. We wanted to completely decouple the decryption method from the sharing method and the share representation, i.e. not use the customization string from the checksums in decryption, and I believe avoiding the mention of shamir in the PBKDF2 salt is right, because it allows us to cleanly update backups even to different secret sharing schemes in the future if we want.

**Comment by andrewkozlik** [comment]
https://github.com/trezor/python-shamir-mnemonic/commit/706934d84a7eccff7854133c2fb681ef90658a9e breaks generate_vectors.py, line 66:
```py
mnemonic = wordlist.mnemonic_from_indices(
    indices + rs1024.create_checksum(indices, False)
)

```

**Comment by matejcik** [comment]
LGTM, go ahead

**Pull request merged**
