### PR TITLE
Add tests to CLI

### PR DESCRIPTION
**Pull request by infokiller**

### CODE REVIEW

**Comment by matejcik** [comment]
let's not add hand-written test harnesses when there is a [recommended way](https://click.palletsprojects.com/en/7.x/testing/) to do this

**Comment by matejcik** [comment]
To be more concrete, I don't want to have to run tests in a convoluted way, when right now you just type `pytest` and it runs what it needs. Any additional tests should also be invoked through pytest. And Click provides a nice facility for simple CLI testing, so that's the tool you should use if you want to implement tests for the CLI

**Comment by jonathancross** [comment]
@infokiller  Can these be added to https://github.com/trezor/python-shamir-mnemonic/blob/master/test_shamir.py ?

**Comment by infokiller** [comment]
I'll look into adding the tests using click

**Comment by matejcik** [comment]
@jonathancross let's also not stuff everything into the same file, alright? :)

**Pull request closed without merging**
